### ISSUE TITLE
Small issue in Devices.prototype.deleteStreamValues()

### ISSUE THREAD

**Issue by UsaidPro** [attm2x/m2x-javascript#14]
In Devices.prototype.deleteStreamValue() (declared in devices.js), it is like this:

    Devices.prototype.deleteStreamValues = function(id, name, params, callback, errorCallback) {
        return this.del(
            helpers.url("/devices/{0}/streams/{1}/values", id, name),
            { params: params },
            callback, errorCallback
        );
    };
However, when I try to use this function, my developer console would output an error saying "no such function as this.del()". To fix this, I found that this code worked:

    Devices.prototype.deleteStreamValues = function(id, name, params, callback, errorCallback) {
        return this.client.del(
            helpers.url("/devices/{0}/streams/{1}/values", id, name),
            { params: params },
            callback, errorCallback
        );
    };
This let me successfully remove my intended values (without outputting an error). Turns out that there is no function '.del()' for a devices/M2X object. Instead, the function is in client.js (and all other functions that call '.del()' use 'this.client.del()'. If this was intended, then sorry! However, I felt like this was a typo that should be fixed.

**Comment by fsaravia** [comment]
@UsaidPro: thanks for the report! You can find a fixed release [here](https://github.com/attm2x/m2x-javascript/releases/tag/3.0.1)
