### ISSUE TITLE
Iterate Over Devices Example

### ISSUE THREAD

**Issue by sankarsubramanian** [attm2x/m2x-javascript#24]
Iterate Over List of Devices: this example should List Devices and then show how to iterate over the paginated list of devices that is returned by the API.

Here's a similar example in Python:
https://github.com/attm2x/m2x-python/blob/master/examples/iterate_over_devices.py

**Comment by majidabdul** [comment]
@kristinpeterson : This issue has been fixed with https://github.com/attm2x/m2x-javascript/pull/26
