### ISSUE TITLE
Add Export Values Example

### ISSUE THREAD

**Issue by sankarsubramanian** [attm2x/m2x-javascript#25]
Export Values from All Data Streams of a Device: this example should first make a call to Export All Values then it should call the View Job Results endpoint until the export job is completed. Then when the Job is complete the example should get the result.url which is the URL where the CSV export can be downloaded.

**Comment by majidabdul** [comment]
@kristinpeterson : This issue has been fixed with https://github.com/attm2x/m2x-javascript/pull/27
