### ISSUE TITLE
Example

### ISSUE THREAD

**Issue by lguadagna** [attm2x/m2x-javascript#30]
index.html reference for the following file : 

```
 <script src="../dist/m2x-3.3.0.js"></script>
```

does not exist in the distro...

I modified the reference to "../src/m2x.js" to try to get a correct reference, then the next error comes which is

```
m2x.js:1 Uncaught ReferenceError: define is not defined
    at m2x.js:1
```

It would be nice to have a working javascript example without a build. thanks.

**Comment by mentos** [comment]
@lguadagna thank you for reporting this. I've included a pre-built version of the `m2x` lib to `dist/` so next time you'll clone or pull for updates the examples page should play out of the box.
