### ISSUE TITLE
Confusion around Params

### ISSUE THREAD

**Issue by sb8244** [attm2x/m2x-javascript#8]
When using `m2x.devices.create(params)`, it would be logical that params is an object like `{ name: "test" }`. However, the library encodes the HTTP request body as `undefined` in this case. Upon digging, I found that the correct format is `{ params: { name: "test" } }` which is mighty confusing.

**Comment by stream7** [comment]
Hi @sb8244 

We agree that a signature like the one you suggest would be more intuitive but we are already planning a new major version/refactoring for this library with many more changes so we'll have to ask you to wait until it's ready :)

Thank you for your feedback!

**Comment by stream7** [comment]
@sb8244 sorry just realised that all the other endpoints have a signature like the one you describe. We'll update this soon.

**Comment by stream7** [comment]
Fixed in [2.0.4](https://github.com/attm2x/m2x-javascript/tree/2.0.4)
